nuls2:
    chain_id: 1
    enabled: False
    packing_node: False
    sync_address: NULSd6HgUkssMi6oSjwEn3puNSijLKnyiRV7H
    api_url: https://apiserver.nuls.io/
    explorer_url: https://nuls.world/
    token_contract: NULSd6Hh1FjbnAktH1FFvFnTzfgFnZtgAhYut

ethereum:
    enabled: False
#    api_url: {{ ALEPH_ETHEREUM_URL }}
    chain_id: 1
    packing_node: False
    sync_contract: "0x166fd4299364B21c7567e163d85D78d2fb2f8Ad5"
    start_height: 11474360
    token_contract: "0x27702a26126e0B3702af63Ee09aC4d1A084EF628"
    token_start_height: 10939074

binancechain:
    enabled: False
    packing_node: False

mongodb:
    uri: "mongodb://localhost:27017"
    database: aleph

storage:
    store_files: true
    engine: mongodb

ipfs:
    enabled: True
    host: localhost
    port: 5001
    gateway_port: 8080

aleph:
    queue_topic: ALEPH-TEST

p2p:
    host: 0.0.0.0
    http_port: 4024
    port: 4025
    control_port: 4030
    reconnect_delay: 60

sentry:
    dsn: null
