nuls2:
    chain_id: 1
    enabled: False
    packing_node: False
    sync_address: NULSd6HgUkssMi6oSjwEn3puNSijLKnyiRV7H
    api_url: https://apiserver.nuls.io/
    explorer_url: https://nuls.world/
    token_contract: NULSd6Hh1FjbnAktH1FFvFnTzfgFnZtgAhYut

ethereum:
    enabled: True
    api_url: {{ ALEPH_ETHEREUM_URL }}
    chain_id: 4
    packing_node: False
    sync_contract: "0x6aDF64fC26D495445A3CAB545aC808d66932aC15"
    start_height: 5042280
    token_contract: "0xc0134b5b924c2fca106efb33c45446c466fbe03e"

binancechain:
    enabled: True
    packing_node: False

mongodb:
    uri: "mongodb://mongodb:27017"
    database: aleph

storage:
    store_files: true
    engine: mongodb

ipfs:
    enabled: True
    host: ipfs
    port: 5001
    gateway_port: 8080

aleph:
    queue_topic: ALEPH-TEST

p2p:
    host: 0.0.0.0
    port: 4025
    http_port: 4024
    reconnect_delay: 60

sentry:
    dsn: null
