version: '2.4'

volumes:
  pyaleph-ipfs:
  pyaleph-mongodb:

services:
  pyaleph:
    restart: always
    image: alephim/pyaleph-node:beta
    command: pyaleph --config /opt/pyaleph/config.yml
    ports:
      - 127.0.0.1:8000:8000/tcp
      - 4024:4024/tcp
      - 4025:4025/tcp
    volumes:
      - ./config.yml:/opt/pyaleph/config.yml
      - ./node-secret.key:/opt/pyaleph/node-secret.key
    depends_on:
      - mongodb
      - ipfs
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  ipfs:
    restart: always
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
    volumes:
      - "pyaleph-ipfs:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment"]

  mongodb:
    restart: always
    image: mongo:3.6
    volumes:
      - pyaleph-mongodb:/data/db
    command: mongod --storageEngine wiredTiger
    networks:
      - pyaleph

networks:
  pyaleph:
